### ISSUE TITLE
[Contract] Airdropper

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/Move-Airdropper-Based-On-Github#4]
0x1） `airdrop_coin_with_average(aptos_addr_list, total_money)`

用 total_money 除以总人数对名单里的人员进行空投

0x2） `airdrop_nft(aptos_addr_list, nft_resources)`

用某个 NFT 对名单里的人员进行空投

0x3）可以将 NFT 和 Coin 转入合约并提取

0x4）用 Event 记录各项行为

0x5）用户的`Claim`

**Comment by zven21** [comment]
🙋🏻‍♀️

**Comment by zven21** [comment]
https://github.com/NonceGeek/Airdropper-Based-On-Github/pull/5
